In [63]:
import pandas as pd

In [64]:
df = pd.read_csv(
    "Database export - Clothing distribuiton EMEA - 2019-2021.csv", encoding="latin1"
)

In [65]:
df.drop("Unnamed: 0", axis=1, inplace=True)

In [66]:
df.head()

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in Original language,...,Website,Operating result [=EBIT]\nmEUR 2021,Operating result [=EBIT]\nmEUR 2020,Operating result [=EBIT]\nmEUR 2019,Turnover\nmEUR 2021,Turnover\nmEUR 2020,Turnover\nmEUR 2019,Availability of financial data,2 years of consecutive losses,Average loss over 3 years
0,ITX HELLAS SINGLE MEMBER S.A.,GR,Grèce,ATHENS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of fashion clothing,Retail,NaN,...,www.zara.com\nwww.fashionwear1.gr,31,17,22,459,352,300,YES,NO,NO
1,RANDEVU,RU,Fédération de Russie,MOSCOW,"UL. SKAKOVAYA D. 17, STR. 2, KOM. 2",4772,Commerce de détail de chaussures et d'articles...,Engaged in the wholesale trade and marketing o...,Wholesale,?????????? ????? ? ???????????,...,www.rendez-vous.ru\nwww.rest-randevu.ru,15,14,1,306,230,337,YES,NO,NO
2,ZEEMAN TEXTIELSUPERS,FR,France,PARIS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail sale of clothing and out...,Retail,"Négoce au détail ou en gros de vêtements, acce...",...,www.zeeman.com,4,3,4,164,137,147,YES,NO,NO
3,ANSWEAR.COM S.A.,PL,Pologne,KRAKOW,NaN,4771,Commerce de détail d'habillement en magasin sp...,Digital platform for the sale of branded cloth...,Wholesale; Retail; Services,NaN,...,www.answear.com,8,5,1,149,90,73,YES,NO,NO
4,REGENT GOLD,RU,Fédération de Russie,"AGALATOVSKOE SELSKOE POSELENIE, D. SKOTNOE","UL. SAVUSHKINA D. 126, LIT. A, POMESHCH. 133-N",4777,Commerce de détail d'articles d'horlogerie et ...,Operates as other miscellaneous store retailer,Retail,???????? ?????????? ?????????,...,www.zolotoy.ru,22,16,5,141,103,117,YES,NO,NO

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Company Name                         490 non-null    object
 1   ISO Country Code                     490 non-null    object
 2   Country                              490 non-null    object
 3   City                                 490 non-null    object
 4   Address                              218 non-null    object
 5   NACE Rev. 2 Code principal           490 non-null    int64
 6   NACE Principal Rev. 2, description   490 non-null    object
 7   Sector                               322 non-null    object
 8   Main activity                        322 non-null    object
 9   Description in Original language     339 non-null    object
 10  Description in English               346 non-null    object
 11  Website                              436 non-null    object
 12  Operating result [=EBIT]
mEUR 2021   490 non-null    object
 13  Operating result [=EBIT]
mEUR 2020   490 non-null    object
 14  Operating result [=EBIT]
mEUR 2019   490 non-null    object
 15  Turnover
mEUR 2021                   490 non-null    int64
 16  Turnover
mEUR 2020                   490 non-null    int64
 17  Turnover
mEUR 2019                   490 non-null    int64
 18  Availability of financial data       490 non-null    object
 19  2 years of consecutive losses        490 non-null    object
 20  Average loss over 3 years            439 non-null    object
dtypes: int64(4), object(17)
memory usage: 80.5+ KB

In [68]:
# ✅ 1. Clean Column Names
df.columns = [col.replace("\n", " ").strip() for col in df.columns]

In [69]:
# ✅ 2. Convert Financial Columns to Numeric
financial_cols = [
    "Operating result [=EBIT] mEUR 2021",
    "Operating result [=EBIT] mEUR 2020",
    "Operating result [=EBIT] mEUR 2019",
    "Turnover mEUR 2021",
    "Turnover mEUR 2020",
    "Turnover mEUR 2019",
]
df[financial_cols] = df[financial_cols].apply(pd.to_numeric, errors="coerce")

In [70]:
# ✅ 3. Handle Missing Values
df["Website"] = df["Website"].fillna("No Website")  # Replace missing websites
df.dropna(subset=["Description in English"], inplace=True)

In [71]:
# ✅ 4. Extract First Website from Multi-Entry Fields
df["Website"] = df["Website"].apply(
    lambda x: x.split("\n")[0] if isinstance(x, str) else x
)

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 346 entries, 0 to 488
Data columns (total 21 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Company Name                        346 non-null    object
 1   ISO Country Code                    346 non-null    object
 2   Country                             346 non-null    object
 3   City                                346 non-null    object
 4   Address                             141 non-null    object
 5   NACE Rev. 2 Code principal          346 non-null    int64
 6   NACE Principal Rev. 2, description  346 non-null    object
 7   Sector                              322 non-null    object
 8   Main activity                       322 non-null    object
 9   Description in Original language    232 non-null    object
 10  Description in English              346 non-null    object
 11  Website                             346 non-null    object
 12  Operating result [=EBIT] mEUR 2021  344 non-null    float64
 13  Operating result [=EBIT] mEUR 2020  344 non-null    float64
 14  Operating result [=EBIT] mEUR 2019  344 non-null    float64
 15  Turnover mEUR 2021                  346 non-null    int64
 16  Turnover mEUR 2020                  346 non-null    int64
 17  Turnover mEUR 2019                  346 non-null    int64
 18  Availability of financial data      346 non-null    object
 19  2 years of consecutive losses       346 non-null    object
 20  Average loss over 3 years           304 non-null    object
dtypes: float64(3), int64(4), object(14)
memory usage: 59.5+ KB

In [73]:
df.drop(["Description in Original language"], axis=1, inplace=True)

In [74]:
df

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in English,Website,Operating result [=EBIT] mEUR 2021,Operating result [=EBIT] mEUR 2020,Operating result [=EBIT] mEUR 2019,Turnover mEUR 2021,Turnover mEUR 2020,Turnover mEUR 2019,Availability of financial data,2 years of consecutive losses,Average loss over 3 years
0,ITX HELLAS SINGLE MEMBER S.A.,GR,Grèce,ATHENS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of fashion clothing,Retail,"Exclusive imports and trade of garments, shoes...",www.zara.com,31.0,17.0,22.0,459,352,300,YES,NO,NO
1,RANDEVU,RU,Fédération de Russie,MOSCOW,"UL. SKAKOVAYA D. 17, STR. 2, KOM. 2",4772,Commerce de détail de chaussures et d'articles...,Engaged in the wholesale trade and marketing o...,Wholesale,Engaged in the wholesale trade and marketing o...,www.rendez-vous.ru,15.0,14.0,1.0,306,230,337,YES,NO,NO
2,ZEEMAN TEXTIELSUPERS,FR,France,PARIS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail sale of clothing and out...,Retail,Engaged in the retail sale of clothing and out...,www.zeeman.com,4.0,3.0,4.0,164,137,147,YES,NO,NO
3,ANSWEAR.COM S.A.,PL,Pologne,KRAKOW,NaN,4771,Commerce de détail d'habillement en magasin sp...,Digital platform for the sale of branded cloth...,Wholesale; Retail; Services,The main activities of the Company are Electro...,www.answear.com,8.0,5.0,1.0,149,90,73,YES,NO,NO
4,REGENT GOLD,RU,Fédération de Russie,"AGALATOVSKOE SELSKOE POSELENIE, D. SKOTNOE","UL. SAVUSHKINA D. 126, LIT. A, POMESHCH. 133-N",4777,Commerce de détail d'articles d'horlogerie et ...,Operates as other miscellaneous store retailer,Retail,Operates as other miscellaneous store retailer...,www.zolotoy.ru,22.0,16.0,5.0,141,103,117,YES,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
482,BIJOUX BOUTIQUE,FR,France,STRASBOURG,NaN,4777,Commerce de détail d'articles d'horlogerie et ...,Operates as a retailer of miscellaneous shoppi...,Retail,Operates as a retailer of miscellaneous shoppi...,www.boutiquesobijoux.com,1.0,1.0,0.0,4,5,5,YES,NO,NO
483,PRO RETAIL FINLAND OY,FI,Finlande,ESPOO,C/O KOTKAN TILIPALVELU OY KIRKKOKATU 18,4771,Commerce de détail d'habillement en magasin sp...,NaN,NaN,"Yhtion toimialana on vaatteiden-, jalkineiden-...",www.isoomena.fi,0.0,0.0,0.0,4,4,5,YES,NO,NO
484,BIONDI S.R.L.,IT,Italie,VERCELLI,CORSO LIBERTA' 41,4777,Commerce de détail d'articles d'horlogerie et ...,Primarily engaged in the wholesale trade of je...,Wholesale,Primarily engaged in the wholesale trade of je...,www.biondigioielli.com,1.0,1.0,1.0,4,5,6,YES,NO,NO
487,ZETEK SRL,IT,Italie,CERVIA,VIALE ROMAGNA 69/71,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and retail sale of ...,Manufacturing; Retail,Engaged in the manufacture and retail sale of ...,www.tezuk.com,0.0,0.0,0.0,4,4,5,YES,NO,NO
488,WADEL S.R.L.,IT,Italie,CAGLIARI,VIA DEL RISORGIMENTO 5,4772,Commerce de détail de chaussures et d'articles...,Primarily engaged in the retail sale of footwe...,Retail,Primarily engaged in the retail sale of footwe...,www.cralregionesardegna.it/?p=2693,0.0,0.0,1.0,4,6,10,YES,NO,NO

In [75]:
df["NACE Rev. 2 Code principal"].unique()

array([4771, 4772, 4777, 4751, 4641, 4511, 2611])

| NACE Code | Description                                                                 |
|-----------|-----------------------------------------------------------------------------|
| 4771      | Retail sale of clothing in specialized stores ✅ (Relevant for luxury filtering) |
| 4772      | Retail sale of footwear and leather goods ✅ (Luxury possible, needs filtering) |
| 4777      | Retail sale of watches and jewelry in specialized stores ✅ (Luxury brands possible) |
| 4751      | Retail sale of textiles (e.g., fabrics, not clothing) ❌ (Likely irrelevant) |
| 4641      | Wholesale of textiles ❌ (Not a retailer, likely irrelevant) |
| 4511      | Sale of motor vehicles ❌ (Not relevant to clothing/luxury) |
| 2611      | Manufacture of electronic components ❌ (Completely irrelevant) |
| 4764      | Retail sale of sports goods ❌ (Sports-focused, unlikely to be luxury) |
| 4615      | Wholesale of furniture, carpets, lighting equipment ❌ (Irrelevant) |

In [76]:
# relevant NACE codes
codes = [4771, 4772, 4777]

In [77]:
# Keep only rows with relevant NACE codes
df = df[df["NACE Rev. 2 Code principal"].isin(codes)]

In [79]:
df

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in English,Website,Operating result [=EBIT] mEUR 2021,Operating result [=EBIT] mEUR 2020,Operating result [=EBIT] mEUR 2019,Turnover mEUR 2021,Turnover mEUR 2020,Turnover mEUR 2019,Availability of financial data,2 years of consecutive losses,Average loss over 3 years
0,ITX HELLAS SINGLE MEMBER S.A.,GR,Grèce,ATHENS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of fashion clothing,Retail,"Exclusive imports and trade of garments, shoes...",www.zara.com,31.0,17.0,22.0,459,352,300,YES,NO,NO
1,RANDEVU,RU,Fédération de Russie,MOSCOW,"UL. SKAKOVAYA D. 17, STR. 2, KOM. 2",4772,Commerce de détail de chaussures et d'articles...,Engaged in the wholesale trade and marketing o...,Wholesale,Engaged in the wholesale trade and marketing o...,www.rendez-vous.ru,15.0,14.0,1.0,306,230,337,YES,NO,NO
2,ZEEMAN TEXTIELSUPERS,FR,France,PARIS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail sale of clothing and out...,Retail,Engaged in the retail sale of clothing and out...,www.zeeman.com,4.0,3.0,4.0,164,137,147,YES,NO,NO
3,ANSWEAR.COM S.A.,PL,Pologne,KRAKOW,NaN,4771,Commerce de détail d'habillement en magasin sp...,Digital platform for the sale of branded cloth...,Wholesale; Retail; Services,The main activities of the Company are Electro...,www.answear.com,8.0,5.0,1.0,149,90,73,YES,NO,NO
4,REGENT GOLD,RU,Fédération de Russie,"AGALATOVSKOE SELSKOE POSELENIE, D. SKOTNOE","UL. SAVUSHKINA D. 126, LIT. A, POMESHCH. 133-N",4777,Commerce de détail d'articles d'horlogerie et ...,Operates as other miscellaneous store retailer,Retail,Operates as other miscellaneous store retailer...,www.zolotoy.ru,22.0,16.0,5.0,141,103,117,YES,NO,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,BIJOUX BOUTIQUE,FR,France,STRASBOURG,NaN,4777,Commerce de détail d'articles d'horlogerie et ...,Operates as a retailer of miscellaneous shoppi...,Retail,Operates as a retailer of miscellaneous shoppi...,www.boutiquesobijoux.com,1.0,1.0,0.0,4,5,5,YES,NO,NO
327,PRO RETAIL FINLAND OY,FI,Finlande,ESPOO,C/O KOTKAN TILIPALVELU OY KIRKKOKATU 18,4771,Commerce de détail d'habillement en magasin sp...,NaN,NaN,"Yhtion toimialana on vaatteiden-, jalkineiden-...",www.isoomena.fi,0.0,0.0,0.0,4,4,5,YES,NO,NO
328,BIONDI S.R.L.,IT,Italie,VERCELLI,CORSO LIBERTA' 41,4777,Commerce de détail d'articles d'horlogerie et ...,Primarily engaged in the wholesale trade of je...,Wholesale,Primarily engaged in the wholesale trade of je...,www.biondigioielli.com,1.0,1.0,1.0,4,5,6,YES,NO,NO
329,ZETEK SRL,IT,Italie,CERVIA,VIALE ROMAGNA 69/71,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and retail sale of ...,Manufacturing; Retail,Engaged in the manufacture and retail sale of ...,www.tezuk.com,0.0,0.0,0.0,4,4,5,YES,NO,NO
330,WADEL S.R.L.,IT,Italie,CAGLIARI,VIA DEL RISORGIMENTO 5,4772,Commerce de détail de chaussures et d'articles...,Primarily engaged in the retail sale of footwe...,Retail,Primarily engaged in the retail sale of footwe...,www.cralregionesardegna.it/?p=2693,0.0,0.0,1.0,4,6,10,YES,NO,NO

In [80]:
df["Main activity"].unique()

array(['Retail', 'Wholesale', 'Wholesale; Retail; Services',
       'Manufacturing; Retail', 'Manufacturing', 'Services',
       'Retail; Services', nan, 'Wholesale; Retail',
       'Manufacturing; Wholesale', 'Manufacturing; Retail; Services',
       'Wholesale; Services'], dtype=object)

In [82]:
relevant_main_activity = [
    "Retail",
    "Wholesale; Retail; Services",
    "Manufacturing; Retail",
    "Retail; Services",
    "Wholesale; Retail",
    "Manufacturing; Retail; Services",
]

df = df[df["Main activity"].isin(relevant_main_activity)]

In [83]:
df

,Company Name,ISO Country Code,Country,City,Address,NACE Rev. 2 Code principal,"NACE Principal Rev. 2, description",Sector,Main activity,Description in English,Website,Operating result [=EBIT] mEUR 2021,Operating result [=EBIT] mEUR 2020,Operating result [=EBIT] mEUR 2019,Turnover mEUR 2021,Turnover mEUR 2020,Turnover mEUR 2019,Availability of financial data,2 years of consecutive losses,Average loss over 3 years
0,ITX HELLAS SINGLE MEMBER S.A.,GR,Grèce,ATHENS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail of fashion clothing,Retail,"Exclusive imports and trade of garments, shoes...",www.zara.com,31.0,17.0,22.0,459,352,300,YES,NO,NO
2,ZEEMAN TEXTIELSUPERS,FR,France,PARIS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail sale of clothing and out...,Retail,Engaged in the retail sale of clothing and out...,www.zeeman.com,4.0,3.0,4.0,164,137,147,YES,NO,NO
3,ANSWEAR.COM S.A.,PL,Pologne,KRAKOW,NaN,4771,Commerce de détail d'habillement en magasin sp...,Digital platform for the sale of branded cloth...,Wholesale; Retail; Services,The main activities of the Company are Electro...,www.answear.com,8.0,5.0,1.0,149,90,73,YES,NO,NO
4,REGENT GOLD,RU,Fédération de Russie,"AGALATOVSKOE SELSKOE POSELENIE, D. SKOTNOE","UL. SAVUSHKINA D. 126, LIT. A, POMESHCH. 133-N",4777,Commerce de détail d'articles d'horlogerie et ...,Operates as other miscellaneous store retailer,Retail,Operates as other miscellaneous store retailer...,www.zolotoy.ru,22.0,16.0,5.0,141,103,117,YES,NO,NO
6,NILSON GROUP AB FILIAL NORGE,NO,Norvège,OSLO,NaN,4772,Commerce de détail de chaussures et d'articles...,Engaged in the operation of a chain of shoe st...,Retail,Engaged in the operation of a chain of shoe st...,No Website,-2.0,-20.0,-6.0,120,125,191,YES,YES,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,MARMON SPORTS,FR,France,AUBERVILLIERS,NaN,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail trade of sporting goods ...,Retail,Engaged in the retail trade of sporting goods ...,marmonsports.com,0.0,0.0,0.0,4,5,6,YES,NO,NO
325,MODA CENTER S.R.L.,IT,Italie,TREVIGNANO,VIA TREVISO 71,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the retail trade of wearing apparel...,Retail,Engaged in the retail trade of wearing apparel...,www.puntoettore.it,-2.0,-5.0,0.0,4,5,8,YES,YES,NaN
326,BIJOUX BOUTIQUE,FR,France,STRASBOURG,NaN,4777,Commerce de détail d'articles d'horlogerie et ...,Operates as a retailer of miscellaneous shoppi...,Retail,Operates as a retailer of miscellaneous shoppi...,www.boutiquesobijoux.com,1.0,1.0,0.0,4,5,5,YES,NO,NO
329,ZETEK SRL,IT,Italie,CERVIA,VIALE ROMAGNA 69/71,4771,Commerce de détail d'habillement en magasin sp...,Engaged in the manufacture and retail sale of ...,Manufacturing; Retail,Engaged in the manufacture and retail sale of ...,www.tezuk.com,0.0,0.0,0.0,4,4,5,YES,NO,NO
330,WADEL S.R.L.,IT,Italie,CAGLIARI,VIA DEL RISORGIMENTO 5,4772,Commerce de détail de chaussures et d'articles...,Primarily engaged in the retail sale of footwe...,Retail,Primarily engaged in the retail sale of footwe...,www.cralregionesardegna.it/?p=2693,0.0,0.0,1.0,4,6,10,YES,NO,NO

In [84]:
df.reset_index(drop=True, inplace=True)

In [ ]:
df.to_csv